# Basic configuration
homeassistant:
  name: Home
  latitude: YOUR_LATITUDE
  longitude: YOUR_LONGITUDE
  elevation: YOUR_ELEVATION
  unit_system: metric
  time_zone: America/Los_Angeles
  external_url: "https://yourdomain.com"
  internal_url: "http://192.168.1.100:8123"

# Enable the frontend
frontend:

# Enable configuration UI
config:

# System Health
system_health:

# Discover integrations
default_config:

# Text to speech
tts:
  - platform: google_translate

# Google Assistant integration for your use case
google_assistant:
  project_id: weavehacks
  service_account: !include SERVICE_ACCOUNT.JSON
  report_state: true
  exposed_domains:
    - script
    - input_text
    - sensor

# REST commands for your API
rest_command:
  ask_api_endpoint:
    url: "https://weavehacks-833206055650.us-central1.run.app/prompt"
    method: POST
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ states('input_text.api_token') }}"
    payload: '{"query": "{{ query }}"}'
    timeout: 30

# Sensors to store API responses
sensor:
  - platform: rest
    name: api_response
    resource: https://weavehacks-833206055650.us-central1.run.app/prompt/status
    value_template: "{{ value_json.response }}"
    scan_interval: 86400  # Only update when triggered

# Input text for storing temporary data
input_text:
  api_query:
    name: API Query
    initial: ""
  api_token:
    name: API Token
    initial: "your-api-token-here"
    mode: password

# Include other configuration files
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml